# Build Windows installer using Inno Setup
# Usage: .\build-windows-installer.ps1 [version]

param(
    [string]$Version = ""
)

$ErrorActionPreference = "Stop"

# Get script directory and project root
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = (Get-Item $ScriptDir).Parent.Parent.FullName
Set-Location $ProjectRoot

# Get version from pubspec.yaml if not provided
if ([string]::IsNullOrEmpty($Version)) {
    $PubspecContent = Get-Content "pubspec.yaml"
    $VersionLine = $PubspecContent | Where-Object { $_ -match '^version:\s+(.+)' }
    if ($VersionLine) {
        $Version = ($VersionLine -split '\s+')[1] -split '\+' | Select-Object -First 1
    } else {
        Write-Error "Could not find version in pubspec.yaml"
        exit 1
    }
}

$AppName = "project_launcher"
$AppDisplayName = "Project Launcher"
$Publisher = "Project Launcher Team"
$BuildDir = "$ProjectRoot\build\windows\x64\runner\Release"

Write-Host "Building Windows installer for version $Version" -ForegroundColor Green

# Check if build exists
if (-not (Test-Path $BuildDir)) {
    Write-Error "Build directory not found. Run 'flutter build windows --release' first."
    exit 1
}

# Create output directory
$OutputDir = "$ProjectRoot\dist\windows"
New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

# ============================================================
# 1. Create ZIP archive
# ============================================================
Write-Host "Creating ZIP archive..." -ForegroundColor Cyan
$ZipFile = "$OutputDir\$AppName-$Version-windows-x64.zip"
Compress-Archive -Path "$BuildDir\*" -DestinationPath $ZipFile -Force
Write-Host "✓ ZIP archive created: $AppName-$Version-windows-x64.zip" -ForegroundColor Green

# ============================================================
# 2. Install Inno Setup if not present
# ============================================================
$InnoSetupPath = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
if (-not (Test-Path $InnoSetupPath)) {
    Write-Host "Installing Inno Setup..." -ForegroundColor Cyan

    if (Get-Command choco -ErrorAction SilentlyContinue) {
        choco install innosetup -y
    } else {
        Write-Warning "Inno Setup not found. Please install it manually from:"
        Write-Warning "https://jrsoftware.org/isdl.php"
        Write-Warning "Or install Chocolatey and run: choco install innosetup"
        exit 1
    }
}

# ============================================================
# 3. Create Inno Setup script
# ============================================================
Write-Host "Creating Inno Setup script..." -ForegroundColor Cyan

# Generate a GUID for UpgradeCode (should be the same across versions)
# In production, use a fixed GUID
$AppGuid = "{12345678-1234-1234-1234-123456789ABC}"

$InnoScript = @"
; Inno Setup Script for $AppDisplayName
; Generated by build-windows-installer.ps1

#define MyAppName "$AppDisplayName"
#define MyAppVersion "$Version"
#define MyAppPublisher "$Publisher"
#define MyAppURL "https://github.com/your-repo/project_launcher"
#define MyAppExeName "$AppName.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId=$AppGuid
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=$ProjectRoot\LICENSE
OutputDir=$OutputDir
OutputBaseFilename=$AppName-$Version-windows-x64-installer
SetupIconFile=$ProjectRoot\windows\runner\resources\app_icon.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
UninstallDisplayIcon={app}\{#MyAppExeName}
VersionInfoVersion={#MyAppVersion}
VersionInfoCompany={#MyAppPublisher}
VersionInfoDescription={#MyAppName} Installer
VersionInfoProductName={#MyAppName}
VersionInfoProductVersion={#MyAppVersion}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 6.1; Check: not IsAdminInstallMode

[Files]
Source: "$BuildDir\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function InitializeSetup(): Boolean;
var
  ResultCode: Integer;
  UninstallerPath: String;
begin
  Result := True;

  // Check if an old version is installed
  if RegQueryStringValue(HKLM, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\$AppGuid_is1', 'UninstallString', UninstallerPath) then
  begin
    if MsgBox('A previous version of $AppDisplayName is installed. Do you want to uninstall it first?', mbConfirmation, MB_YESNO) = IDYES then
    begin
      // Run the uninstaller
      Exec(RemoveQuotes(UninstallerPath), '/SILENT', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    end;
  end;
end;

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
"@

$InnoScriptPath = "$ProjectRoot\installer.iss"
$InnoScript | Out-File -FilePath $InnoScriptPath -Encoding UTF8

Write-Host "✓ Inno Setup script created" -ForegroundColor Green

# ============================================================
# 4. Compile installer
# ============================================================
Write-Host "Compiling installer..." -ForegroundColor Cyan

if (Test-Path $InnoSetupPath) {
    & $InnoSetupPath $InnoScriptPath

    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ Installer created: $AppName-$Version-windows-x64-installer.exe" -ForegroundColor Green
    } else {
        Write-Error "Inno Setup compilation failed with exit code $LASTEXITCODE"
        exit 1
    }
} else {
    Write-Warning "Inno Setup compiler not found at: $InnoSetupPath"
    Write-Warning "The Inno Setup script has been created at: $InnoScriptPath"
    Write-Warning "Please compile it manually or install Inno Setup."
}

# Clean up
if (Test-Path $InnoScriptPath) {
    # Remove-Item $InnoScriptPath
    Write-Host "Note: Inno Setup script saved at: $InnoScriptPath" -ForegroundColor Yellow
}

# ============================================================
# 5. Create portable version
# ============================================================
Write-Host "Creating portable version..." -ForegroundColor Cyan

$PortableDir = "$OutputDir\$AppName-$Version-windows-x64-portable"
New-Item -ItemType Directory -Force -Path $PortableDir | Out-Null

# Copy files
Copy-Item -Path "$BuildDir\*" -Destination $PortableDir -Recurse -Force

# Create README for portable version
@"
$AppDisplayName Portable - Version $Version
==========================================

This is a portable version of $AppDisplayName.
No installation required!

How to Use:
-----------
1. Extract this folder anywhere on your computer
2. Run $AppName.exe
3. That's it!

Features:
---------
- No installation required
- Run from USB drive
- Settings stored in application folder
- Easy to move or backup

System Requirements:
-------------------
- Windows 10 or later (x64)
- No administrator privileges required

Notes:
------
- Windows Defender SmartScreen may show a warning for unsigned apps
  Click "More info" → "Run anyway"
- For system-wide installation, use the installer instead

For more information: https://github.com/your-repo/project_launcher
"@ | Out-File -FilePath "$PortableDir\README.txt" -Encoding UTF8

# Create portable ZIP
$PortableZip = "$OutputDir\$AppName-$Version-windows-x64-portable.zip"
Compress-Archive -Path $PortableDir -DestinationPath $PortableZip -Force
Remove-Item -Path $PortableDir -Recurse -Force

Write-Host "✓ Portable version created: $AppName-$Version-windows-x64-portable.zip" -ForegroundColor Green

# ============================================================
# 6. Generate checksums
# ============================================================
Write-Host "Generating checksums..." -ForegroundColor Cyan

$ChecksumFile = "$OutputDir\checksums.txt"
"SHA256 Checksums for $AppDisplayName $Version`n" | Out-File -FilePath $ChecksumFile -Encoding UTF8
"=" * 60 | Out-File -FilePath $ChecksumFile -Append -Encoding UTF8
"`n" | Out-File -FilePath $ChecksumFile -Append -Encoding UTF8

Get-ChildItem "$OutputDir\*.zip", "$OutputDir\*.exe" | ForEach-Object {
    $Hash = Get-FileHash $_.FullName -Algorithm SHA256
    "$($Hash.Hash)  $($_.Name)" | Out-File -FilePath $ChecksumFile -Append -Encoding UTF8
}

Write-Host "✓ Checksums generated" -ForegroundColor Green

# ============================================================
# Summary
# ============================================================
Write-Host ""
Write-Host "==========================================" -ForegroundColor Green
Write-Host "Windows packages built successfully!" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
Write-Host "Output directory: $OutputDir" -ForegroundColor Cyan
Write-Host ""
Get-ChildItem $OutputDir | Format-Table Name, Length, LastWriteTime
Write-Host ""
Write-Host "Distribution packages:" -ForegroundColor Yellow
Write-Host "  Installer: $AppName-$Version-windows-x64-installer.exe (recommended)" -ForegroundColor White
Write-Host "  Portable:  $AppName-$Version-windows-x64-portable.zip" -ForegroundColor White
Write-Host "  ZIP:       $AppName-$Version-windows-x64.zip" -ForegroundColor White
Write-Host ""

# Code signing warning
Write-Host "⚠️  WARNING: Application is not code-signed" -ForegroundColor Yellow
Write-Host "   Windows SmartScreen will show warnings" -ForegroundColor Yellow
Write-Host "   For production releases, configure code signing with:" -ForegroundColor Yellow
Write-Host "   signtool.exe sign /f certificate.pfx /p password /t http://timestamp.digicert.com file.exe" -ForegroundColor Gray
Write-Host ""
